# Generated by Django 6.0.5 on 2026-05-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactmessage_userreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('product_quality', 'Product Quality'), ('delivery_issue', 'Delivery Issue'), ('customer_service', 'Customer Service'), ('payment_issue', 'Payment Issue'), ('website_issue', 'Website Issue'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional: Upload image related to complaint', null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text='Private reply to user')),
                ('is_announced', models.BooleanField(default=False, help_text='Make this complaint visible to all users')),
                ('announcement_title', models.CharField(blank=True, help_text='Title for public announcement', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='users.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
