# Generated by Django 6.0.5 on 2026-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='announcement_title',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_announced',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('new_product', 'New Product'), ('order', 'Order Update'), ('promotion', 'Promotion'), ('maintenance', 'Maintenance'), ('important', 'Important')], default='general', help_text='Announcement category', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent if needs public announcement'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload image', null=True, upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
